/* 200 motivos del cuaderno Motivos Ritmicos. Generado por extract_motifs.py. */
/* w=redonda, h=blanca, q=negra, e=corchea; cada grupo separado por | es un compás. */
const motifPatterns = [
  'w|hh|qqqq|eeeeeeee', // 1
  'w|hh|eeeeeeee|qqqq', // 2
  'w|qqqq|hh|eeeeeeee', // 3
  'w|qqqq|eeeeeeee|hh', // 4
  'w|eeeeeeee|hh|qqqq', // 5
  'w|eeeeeeee|qqqq|hh', // 6
  'hh|w|qqqq|eeeeeeee', // 7
  'hh|w|eeeeeeee|qqqq', // 8
  'hh|qqqq|w|eeeeeeee', // 9
  'hh|qqqq|eeeeeeee|w', // 10
  'hh|eeeeeeee|w|qqqq', // 11
  'hh|eeeeeeee|qqqq|w', // 12
  'qqqq|w|hh|eeeeeeee', // 13
  'qqqq|w|eeeeeeee|hh', // 14
  'qqqq|hh|w|eeeeeeee', // 15
  'qqqq|hh|eeeeeeee|w', // 16
  'qqqq|eeeeeeee|w|hh', // 17
  'qqqq|eeeeeeee|hh|w', // 18
  'eeeeeeee|w|hh|qqqq', // 19
  'eeeeeeee|w|qqqq|hh', // 20
  'eeeeeeee|hh|w|qqqq', // 21
  'eeeeeeee|hh|qqqq|w', // 22
  'eeeeeeee|qqqq|w|hh', // 23
  'eeeeeeee|qqqq|hh|w', // 24
  'hqq|w|hh|qqqq', // 25
  'hh|hqq|qqqq|eeeeeeee', // 26
  'qqqq|eeeeeeee|hqq|w', // 27
  'eeeeeeee|hh|w|hqq', // 28
  'hqq|hh|qqqq|w', // 29
  'w|hqq|eeeeeeee|qqqq', // 30
  'hh|qqqq|hqq|w', // 31
  'eeeeeeee|w|hqq|hqq', // 32
  'qhq|w|hh|qqqq', // 33
  'w|qhq|qqqq|eeeeeeee', // 34
  'qqqq|hh|qhq|w', // 35
  'qhq|eeeeeeee|qqqq|qhq', // 36
  'qhq|hh|w|qqqq', // 37
  'eeeeeeee|qhq|hh|w', // 38
  'w|hh|qhq|qqqq', // 39
  'hh|eeeeeeee|hqq|qhq', // 40
  'qqh|w|qqqq|hh', // 41
  'eeeeeeee|qqh|qqqq|w', // 42
  'hh|qqqq|qqh|hqq', // 43
  'qqqq|eeeeeeee|hh|qqh', // 44
  'qqh|qhq|hqq|qqqq', // 45
  'eeeeeeee|qqh|hqq|qhq', // 46
  'hh|qqqq|qqh|w', // 47
  'w|eeeeeeee|qhq|qqh', // 48
  'heeee|w|qqqq|hh', // 49
  'eeeeeeee|heeee|hh|qqqq', // 50
  'hqq|qqqq|heeee|eeeeeeee', // 51
  'qhq|eeeeeeee|hqq|heeee', // 52
  'heeee|qqh|qhq|hqq', // 53
  'w|heeee|heeee|hh', // 54
  'qqh|qqqq|heeee|eeeeeeee', // 55
  'hh|qhq|w|heeee', // 56
  'eehee|qqh|heeee|qhq', // 57
  'hqq|eehee|qhq|qqh', // 58
  'eeeeeeee|hqq|eehee|qhq', // 59
  'hqq|qqqq|eeeeeeee|eehee', // 60
  'eehee|hh|eeeeeeee|qqqq', // 61
  'w|eehee|qqqq|hh', // 62
  'qqqq|eehee|eehee|w', // 63
  'hh|hh|w|eehee', // 64
  'eeeeh|eehee|qqh|heeee', // 65
  'qhq|eeeeh|heeee|qqh', // 66
  'qqh|qhq|eeeeh|hqq', // 67
  'eeeeeeee|hqq|qhq|eeeeh', // 68
  'eeeeh|eeeeh|hh|qqqq', // 69
  'w|eeeeh|eeeeh|hh', // 70
  'qqqq|qqh|eeeeh|w', // 71
  'eehee|qhq|eeeeeeee|eeeeh', // 72
  'qqqee|heeee|eehee|eeeeh', // 73
  'eehee|qqqee|qqh|heeee', // 74
  'qhq|heeee|qqqee|qqh', // 75
  'hqq|qqh|qhq|qqqee', // 76
  'qqqee|eeeeeeee|hqq|qhq', // 77
  'eeeeeeee|qqqee|qqqq|hqq', // 78
  'qqqq|qqqee|qqqee|hh', // 79
  'w|hh|qqqq|qqqee', // 80
  'qqeeq|eeeeh|qqqee|eehee', // 81
  'heeee|qqeeq|eehee|qqh', // 82
  'qhq|qqh|qqeeq|hqq', // 83
  'eeeeeeee|qqqq|hqq|qqeeq', // 84
  'qqeeq|hh|w|qqqq', // 85
  'qqqq|qqeeq|qqeeq|heeee', // 86
  'w|eehee|qqeeq|eeeeh', // 87
  'qhq|qqqee|hh|qqeeq', // 88
  'qeeqq|eeeeh|qqqee|qqeeq', // 89
  'qqh|qeeqq|heeee|eehee', // 90
  'hqq|qhq|qeeqq|eeeeeeee', // 91
  'w|qqqq|hh|qeeqq', // 92
  'qeeqq|qqeeq|qqh|eehee', // 93
  'hh|qeeqq|qqeeq|qhq', // 94
  'qqqee|qqqee|qeeqq|qqh', // 95
  'qqeeq|qhq|eehee|qeeqq', // 96
  'eeqqq|qqqee|qqeeq|qeeqq', // 97
  'heeee|eeqqq|eehee|eeeeeeee', // 98
  'hqq|qhq|eeqqq|qqh', // 99
  'heeee|eehee|eeeeh|eeqqq', // 100
  'eeqqq|hqq|qhq|qqh', // 101
  'hh|eeqqq|qqqq|eeeeeeee', // 102
  'w|qeeqq|eeqqq|qhq', // 103
  'qqeeq|hqq|w|eeqqq', // 104
  'qqeeee|eeqqq|qeeqq|qqeeq', // 105
  'qqqee|qqeeee|eeeeh|eehee', // 106
  'qhq|heeee|qqeeee|qqh', // 107
  'eeeeeeee|hqq|qqqq|qqeeee', // 108
  'qqeeee|hh|qqeeq|w', // 109
  'eeqqq|qqeeee|qhq|w', // 110
  'qhq|qeeqq|qqeeee|eeeeh', // 111
  'w|eehee|eeqqq|qqeeee', // 112
  'qeeqee|hh|qqqq|w', // 113
  'eeeeeeee|qeeqee|qhq|hqq', // 114
  'heeee|eehee|qeeqee|qqh', // 115
  'eeeeh|qqqee|qqeeq|qeeqee', // 116
  'qeeqee|qeeqq|eeqqq|qqeeee', // 117
  'qqh|qeeqee|eehee|hqq', // 118
  'eeeeh|qeeqee|qeeqee|qqeeq', // 119
  'qhq|qqeeee|w|qeeqee', // 120
  'eeqqee|eehee|qqeeee|qeeqq', // 121
  'w|eeqqee|qqqee|eeeeh', // 122
  'hqq|eeqqee|eeqqee|w', // 123
  'hh|qqqq|eeeeeeee|eeqqee', // 124
  'eeqqee|hqq|qhq|qqh', // 125
  'heeee|eeqqee|eehee|eeeeh', // 126
  'qqqee|qqeeq|eeqqee|qeeqq', // 127
  'eeqqq|qqeeee|qeeqee|eeqqee', // 128
  'eeqeeq|w|hh|qqqq', // 129
  'eeeeeeee|eeqeeq|hqq|qhq', // 130
  'qqh|heeee|eeqeeq|eehee', // 131
  'eeeeh|qqqee|qqeeq|eeqeeq', // 132
  'eeqeeq|qeeqq|eeqqq|qqeeee', // 133
  'qeeqee|eeqeeq|eeqqee|eeqeeq', // 134
  'hqq|w|eeqeeq|qqh', // 135
  'qeeqq|qeeqq|hqq|eeqeeq', // 136
  'eeeeqq|w|qqh|eeeeeeee', // 137
  'hqq|eeeeqq|eehee|hh', // 138
  'heeee|qqqq|eeeeqq|qhq', // 139
  'qqqq|w|eehee|eeeeqq', // 140
  'eeeeqq|qqh|eeeeeeee|qqqee', // 141
  'heeee|eeeeqq|qqeeq|qhq', // 142
  'hh|qeeqq|eeeeqq|eeqqq', // 143
  'eeeeh|hqq|qqeeee|eeeeqq', // 144
  'qeeeeq|qhq|eeqeeq|qqeeq', // 145
  'qqh|qeeeeq|qqeeee|eeeeh', // 146
  'eeeeqq|qeeqq|qeeeeq|eeqqee', // 147
  'eehee|eeqqq|qeeeeq|qeeeeq', // 148
  'qeeeeq|heeee|qqqee|qeeqee', // 149
  'eehee|qeeeeq|qqqee|hqq', // 150
  'qqqq|qhq|qeeeeq|w', // 151
  'eeeeh|hh|eeeeeeee|qeeeeq', // 152
  'hqee|qeeqee|qqeeq|eeeeeeee', // 153
  'qqh|hqee|qeeqq|hh', // 154
  'hqee|eeqqee|hqee|qqqq', // 155
  'eeqqee|eeqeeq|hqq|hqee', // 156
  'hqee|eeeeqq|eeqqq|eeeeh', // 157
  'qqeeq|hqee|qqeeee|heeee', // 158
  'hqee|qeeeeq|hqee|qqqee', // 159
  'eehee|w|qhq|hqee', // 160
  'heeq|qqeeq|hqq|eehee', // 161
  'eeqeeq|heeq|qqh|eeeeh', // 162
  'eeqqq|w|heeq|eeeeeeee', // 163
  'qeeeeq|qqqee|eehee|heeq', // 164
  'heeq|heeq|qhq|qeeqee', // 165
  'hqee|heeq|hh|eeeeqq', // 166
  'heeq|heeee|heeq|qeeqq', // 167
  'eeqqee|qqqq|qqeeee|heeq', // 168
  'qhee|qqqq|hh|w', // 169
  'hqq|qhee|eeqeeq|qqh', // 170
  'qqqee|eehee|qhee|hh', // 171
  'eeqqee|w|heeee|qhee', // 172
  'qhee|qqeeee|qhq|eeeeh', // 173
  'qqqq|qhee|eeeeqq|eeqqq', // 174
  'hqee|qqeeq|qhee|qeeqq', // 175
  'qeeeeq|eeeeeeee|qeeqee|qhee', // 176
  'qeeh|qhq|eehee|qqqq', // 177
  'w|qeeh|eeeeeeee|heeq', // 178
  'qqh|hh|qeeh|heeee', // 179
  'qeeqee|qeeqq|qeeh|qeeh', // 180
  'qeeh|eeqqee|qqqee|qeeeeq', // 181
  'hqee|qeeh|eeqqq|qhee', // 182
  'eeeeh|qqeeee|qeeh|eeeeqq', // 183
  'heeq|qqeeq|eeqeeq|qeeh', // 184
  'eehq|heeee|qqqee|hqq', // 185
  'eeeeh|eehq|qeeqq|eeeeeeee', // 186
  'hh|eeqqq|eehq|w', // 187
  'qqeeq|qhq|qqeeee|eehq', // 188
  'eehq|qqqq|eehee|qqh', // 189
  'hqee|eehq|qhee|eeqqee', // 190
  'eeeeqq|heeq|eehq|qeeeeq', // 191
  'eeqeeq|qeeqee|qeeh|eehq', // 192
  'eeqh|qqqee|hh|qeeqq', // 193
  'eeqeeq|eeqh|qqeeee|heeee', // 194
  'eeeeh|qeeeeq|eeqh|eeeeeeee', // 195
  'qqqq|eeqqee|hqq|eeqh', // 196
  'eeqh|w|hqee|qqh', // 197
  'heeq|eeqh|eehee|qhee', // 198
  'eehq|eeqqq|eeqh|qhq', // 199
  'qqeeq|eeeeqq|qeeqee|eeqh', // 200
];
